### エラーメッセージ
# テンプレート
# [EXXXX]
# other = こんにちは{{.name}}です。

[E0001]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

[E0002]
other = "データの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0101]
other = "認証に失敗しました。しばらくしてから、もう一度お試しください。"

[E0102]
other = "ユーザ作成に失敗しました。しばらくしてから、もう一度お試しください。"

[E0103]
other = "ユーザー取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0104]
other = "アカウントが停止されています。"

[E0201]
other = "パーティーを取得出来ませんでした。しばらくしてから、もう一度お試しください。"

[E0202]
other = "パーティーの更新に失敗しました。"

[E0301]
other = "ガチャの所得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0302]
other = "ガチャの回数が不正です。"

[E0303]
other = "ガチャを回すために必要なリソースがありません。"

[E0304]
other = "ガチャの抽選に失敗しました。しばらくしてから、もう一度お試しください"

[E0305]
other = "ガチャ情報の更新に失敗しました。"

[E0401]
other = "プレゼントの所得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0402]
other = "プレゼントの受け取りに失敗しました。しばらくしてから、もう一度お試しください。"

[E0403]
other = "プレゼントが存在しません。"

[E0404]
other = "受取済みのプレゼントです。"

[E0501]
other = "キャラクターを所持していません。"

[E0502]
other = "キャラクターの強化に失敗しました。"

[E0503]
other = "キャラクターのレベルが上限に達しています。"

[E0504]
other = "キャラクターの強化に必要な素材が不足しています。"

[E0505]
other = "衣装を所持していません。"

[E0506]
other = "指定したキャラクターの衣装ではありません。"

[E0507]
other = "キャラクター情報の取得に失敗しました。"

[E0601]
other = "ギフトに失敗しました。しばらくしてから、もう一度お試しください。"

[E0602]
other = "ハピネスボックスの所持数が不足しています。"

[E0603]
other = "ギフト情報の取得に失敗しました。"

[E0604]
other = "ギフト情報の更新に失敗しました。"

[E0701]
other = "ADVの所得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0702]
other = "ADVが開放されていません。"

[E0703]
other = "開放済みのADVです。"

[E0801]
other = "カードを所持していません。"

[E0802]
other = "カードの強化に失敗しました。"

[E0803]
other = "カードのレベルが上限に達しています。"

[E0804]
other = "カードの強化に必要な素材が不足しています。"

[E0901]
other = "称号のスロットが不正です。"

[E0902]
other = "称号を所持していません。"

[E0903]
other = "称号の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0904]
other = "背景を所持していません。"

[E1001]
other = "クエストの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1002]
other = "サブクエストの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1003]
other = "イベントクエストの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1004]
other = "クエストの更新に失敗しました。"

[E1101]
other = "お知らせの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1102]
other = "カテゴリーが間違っています。"

[E1201]
other = "シーズンの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1202]
other = "シーズン特効の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1203]
other = "イベントパス情報の取得に失敗しました。"

[E1204]
other = "受け取れる報酬がありません。"

[E1301]
other = "リーグの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1302]
other = "リーグ報酬の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1401]
other = "ステージ情報の取得に失敗しました。"

[E1402]
other = "ステージの作成に失敗しました。"

[E1403]
other = "スタミナが不足しています。"

[E1404]
other = "挑戦回数上限に達しています。"

[E1405]
other = "プレイデータの更新に失敗しました。"

[E1501]
other = "管理者の登録に失敗しました。"

[E1502]
other = "ログインに失敗しました。"

[E1503]
other = "作成に失敗しました。"

[E1504]
other = "更新に失敗しました。"

[E1505]
other = "セッションの有効期限が切れました。"

[E1506]
other = "削除に失敗しました。"

[E1601]
other = "ミッションの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1602]
other = "未達成のミッションです。"

[E1603]
other = "受け取り済みのミッションです。"

[E1604]
other = "報酬を受け取り可能なミッションがありません。"

[E1605]
other = "ミッションの更新に失敗しました。"

[E1606]
other = "レイドミッションの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1701]	
other = "レイドの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E1702]
other = "スタミナが不足しています。"

[E1703]
other = "レイドの更新に失敗しました。"

[E1801]
other = "データの取得に失敗しました。"

[E1901]
other = "Vipの情報の取得に失敗しました。"

[E1902]
other = "スキップ機能は通常プレイ後に使用できます。"

[E1903]
other = "VIP{{ .VipRank }}で解放されます。"

[E2001]
other = "ログインボーナス情報の取得に失敗しました。"

[E2002]
other = "ログインボーナスの受け取りに失敗しました。"

[E2101]
other = "イベントの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E2102]
other = "イベントランキングの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E2103]
other = "イベントクエストの更新に失敗しました。"

[E2201]
other = "ファンクラブ情報の取得に失敗しました。"

[E2202]
other = "ファンクラブランクが不足しています。"

[E2203]
other = "ファンクラブ情報の更新に失敗しました。"

[E2301]
other = "交換に失敗しました。しばらくしてから、もう一度お試しください。"

[E2302]
other = "在庫がありません。"

[E2303]
other = "メダルが足りません。"

[E2304]
other = "交換所の情報の更新に失敗しました。"

[E2401]
other = "EPブーストアイテムを所持していません。"

[E2402]
other = "EPブーストアイテムが足りません。"

[E9801]
other = "報酬の獲得に失敗しました。しばらくしてから、もう一度お試しください。"

[E9901]
other = "不正なリクエストです。"

[E9999]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

### System Message

[GACHA_MESSAGE]
other = "ガチャの結果です。"

[STREAMER_GIFT_GACHA_MESSAGE]
other = "{{ .SenderName }}さんから贈られたギフトガチャの結果です。"

[SENDER_GIFT_GACHA_MESSAGE]
other = "{{ .StreamerName }}さんに贈ったギフトガチャの結果です。"

[STREAMER_GIFT_MESSAGE]
other = "{{ .SenderName }}さんから贈られたギフト報酬です。"

[SENDER_GIFT_MESSAGE]
other = "{{ .StreamerName }}さんに贈ったギフト報酬です。"

[CARD_PRESENT_MESSAGE]
other = "{{ .ReceiveType }}で獲得した報酬です。"

[STREAMER_HAPPY_BOX_RESULT_MESSAGE]
other = "{{ .SenderName }}さんから贈られた{{ .ItemName }}の結果です。"

[SENDER_HAPPY_BOX_RESULT_MESSAGE]
other = "{{ .StreamerName }}さんに贈った{{ .ItemName }}の結果です。"

[IMMEDIATELY_MAINTENANCE_MESSAGE]
other = "緊急メンテナンス中です。"

[STAR_RANK_UP_MESSAGE]
other = "スターランクアップの報酬です。"


[BONUS_GIFT_GACHA_MESSAGE]
other = "{{ .StreamerName }}さんに贈ったおまけガチャの結果です。"

[RANKING_REWARD_MESSAGE]
other = "{{ .RankingKind }}ランキング{{ .Rank }}位の報酬です"