### エラーメッセージ

[E0001]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

[E0002]
other = "データの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0101]
other = "認証に失敗しました。しばらくしてから、もう一度お試しください。"

[E0102]
other = "ユーザ作成に失敗しました。しばらくしてから、もう一度お試しください。"

[E0103]
other = "ユーザー取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0201]
other = "登録可能な取引金額上限を超えています。"

[E9901]
other = "不正なリクエストです。"

[E9999]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"
