version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "3306:3306"
    volumes:
      - ./:/app
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: codetest
    command: ["./start.sh"] 